# Generated by Django 5.2.7 on 2025-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numCarte", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
